### ISSUE TITLE
Project Delta Δ

### ISSUE THREAD

**Issue by Mickkkkkkk** [cybernetisk/internsystem-v2#23]
On the profile page, there's a field you can enter a name/email of who recruited you. Once you enter a neam, it locks in and you can't change it anymore. The collective hours clocked by your recruits in the current semester is a multiplier to how many vouchers you earn when logging hours. For example, if I have recruited 4 people, and they have worked 60 hours in total, my multiplier MIGHT be 60 * 0.001 = 0.06. So the next hour I register, it will be counted as 1 * 1.06 = 1.06 hours. It is supposed to be a joke, but also possible to gain a little from the joke.

**Comment by Mickkkkkkk** [comment]
Features:

- See who've you've recruited on your profile page.
- See your multiplier (either on the profile page, or when registering hours)

**Comment by EricSvebakk** [comment]
Phase I complete
