### ISSUE TITLE
"Register"-button in "Register new user" doesn't do anything.

### ISSUE THREAD

**Issue by reduan1109** [cybernetisk/internsystem-v2#38]
**Describe the bug**
After filling out the registration form and pressing the register button, nothing happens.

**To Reproduce**
1. Go to [Register new user](https://cyb.no/pages/auth/register).
2. Fill out the form.
3. Press REGISTER.
4. Nothing happens.

**Expected behavior**
Expected some form of feedback if the registration worked or did not work.

**Screenshots**
Not applicable at this time.

**Additional context**
Post request to `https://cyb.no/api/createUser`, when pressing REGISTER-button returns `500`.
User-agent is: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:130.0) Gecko/20100101 Firefox/130.0

Might already be registered? Had a user some time ago.

**Comment by EricSvebakk** [comment]
accidentally changed user schema for prisma when merging another feature. Issue fixed. New users can now be registered.
