### ISSUE TITLE
First name instead of "Profile" in right corner of header

### ISSUE THREAD

**Issue by yrjarv** [cybernetisk/internsystem-v2#42]
I think it would be a tiny improvement if the button to go to /pages/main/profile said the user's first name (if they are logged in), instead of the generic "Profile"
This is how it is now:
![image](https://github.com/user-attachments/assets/a256de1b-c08f-477d-9bd1-e59288fdd2ba)
My suggestion:
![image](https://github.com/user-attachments/assets/5977d63e-b054-4b50-9947-fef491796056)

If this issue is accepted and put into the project, I can handle the development of this (quite small) enhancement

**Comment by EricSvebakk** [comment]
This is a useful feature. Make sure to test the Profile Button with variable length names and names with dashes. There is also a WIP textUtil file for getting initials.
