### ISSUE TITLE
Riktig uttale av Cybernetisk Selskab

### ISSUE THREAD

**Issue by ubesluttsom** [cybernetisk/internsystem-v2#43]
Ingen eksterne vet hvordan man uttaler navnet vårt. Kanskje putt IPA av det på forsiden? Typ sånn som Wikipedia artikler gjør det.

> Cybernetisk Selskap ['kʏːbɛrnɛtɪsk ˈsɛlskɑb]

Eller noe sånt.

**Comment by Mickkkkkkk** [comment]
@EricSvebakk I am not språktek, but it looks ish correct

**Comment by EricSvebakk** [comment]
The "About CYB"-page has been updated with the IPA pronunication.
