### ISSUE TITLE
"About Cyb" AppBar breaks into two lines on mobile

### ISSUE THREAD

**Issue by yrjarv** [cybernetisk/internsystem-v2#47]
When testing with very narrow screen dimensions, AppBar "breaks" because of "About Cyb" becoming two lines ("About \n Cyb"). This doesn't look great.
My proposal is that we make it so that when the viewport is smaller than a given threshold, "About Cyb" is shortened to "About".

![Image](https://github.com/user-attachments/assets/46de33be-4bda-4296-8d2b-81b1acd02956)
![Image](https://github.com/user-attachments/assets/b8ca473e-8a99-47c8-9974-20c7bcf48947)

**Comment by EricSvebakk** [comment]
I agree with the suggested change :))
