### ISSUE TITLE
Register half hours

### ISSUE THREAD

**Issue by juliegri** [cybernetisk/internsystem-v2#5]
### Hi!

I recently did a KM-shift in the cafe and worked for 2.5 hours. However, when I went to register my worked hours, it only showed as 2 hours. I tried manually adding 0.5 hours, but it showed as 0 hours worked (and no bongs of course - which might be another issue in it self??). I would like to register this half hour plspls poor student or something 😭

*Best regards Julie*

**Comment by EricSvebakk** [comment]
database and frontend have been updated to allow float-values. Values are rounded to 1 decimal.
