### ISSUE TITLE
Better paths for better usability

### ISSUE THREAD

**Issue by Sebbben** [cybernetisk/internsystem-v2#50]
**Describe the problem you are experiencing**
When currently using the page, the home page is located at /pages/main/home. Same goes for pages like aboutCYB and so on.

**Describe the solution you'd like**
I believe it would be better to have the homepage located at / and profile at /profile and so on

**Describe alternatives you've considered**
Next uses the file structure of the project to generate the url paths, so to make the paths more usable, I see two options:
 1. Restructure the entrire project to better take advantage of nexts auto path generating
 2. Add parenthesis to folders like pages and main to make next ignore these directories when generating paths

**Additional context**
I've tested the latter option, and have gotten the page to work like i imagined using this method.
Only problem is that all links to the page need to be changed to not include the /pages/main part. This includes links i believe are stored in the CMS

**Comment by EricSvebakk** [comment]
Well done. Vouchers have been registered for this medium task.
