### ISSUE TITLE
Halloween theme

### ISSUE THREAD

**Issue by Borgarsy** [cybernetisk/internsystem-v2#65]
Would be cool to change to Halloween theme for since we are now in october. I suggest switching to orange instead of yellow and the penguien for a ghost/pumpkin.

Something like this:
![bilde](https://github.com/user-attachments/assets/78a2ab0a-bfe5-424f-a7a2-02cab8aabf93)
![bilde](https://github.com/user-attachments/assets/e81fd380-aeee-4614-8d99-13c1d1bfe81a)

**Comment by EricSvebakk** [comment]
Hahah, i really like this idea. This could be implemented manually for now, but perhaps we could give users an interface to select themes for their profile in the future?

**Comment by Borgarsy** [comment]
I'll make a temporary pull request to change it to orange now and I'll roll the select theme interface into issue #18 and change it to a genral revamp/upgrade of the user page.

**Comment by EricSvebakk** [comment]
Solved by #75
