### ISSUE TITLE
Membership shows a blank result page if search results are fewer than expected given the page number

### ISSUE THREAD

**Issue by Mickkkkkkk** [cybernetisk/internsystem-v2#66]
The results page shows no members when searching if the results are fewer than what's expected given the current page. I.e. if you're on page 2 and search, and the search gives <11 results, nothing is shown, and the user have to go back to the previous page to see the results. This happened during pub, and opening was delayed with 5 minutes.

1. Go to the membership page.
2. Go to the last page.
3. Search for "Mick" with name/contains filters.
4. Nothing will show up, but it will be possible to move to a previous page until results show up.

**Comment by EricSvebakk** [comment]
Vouchers have been registered for this small task.
